POST http://127.0.0.1:8080/vehicle
Content-Type: application/json


// to test transaction rolback case set car id to 3
{
  "carId": 5,
  "coordinates": {
    "latitude": 121.12,
    "longitude": 71.5646
  }
}
