spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "com.example.kafka"
#      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: record
      concurrency: 3
      type: single
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      transaction-id-prefix: "vehicle"

